### ISSUE TITLE
header

### ISSUE THREAD

**Issue by ghost** [dfelinto/blender-git#61]
hi

Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?
Because '304' seems to me 3.04 but '340' is 3.40 ?

see: https://fossies.org/linux/blender/doc/blender_file_format/mystery_of_the_blend.html

**Comment by dfelinto** [comment]
We did it so if Blender ever gets to 3.10, 3.11 we are ready for it. Even though the plan is to end each series in 2 years so in theory we won' t run into that

**Comment by ghost** [comment]
So is the following correct?

Blender 3.4.1 still gives "304" so is it correct subversions are not written in the file? :) I think because there are only 3 digits and they can't change the convention for subversions.
And "3041" is not possible, there are only 3 digits

So "304" is used to have "some room" for when the version goes from 3.9 to 3.10? The "0" is a sort of place holder?
So then "309" becomes "310" because otherwise they can't fit it in 3 digits.

**Comment by dfelinto** [comment]
Hi, the .1 is a subversion. And stored separately.

See BLENDER_FILE_SUBVERSION in the BKE_blender_version.h

https://projects.blender.org/blender/blender/src/branch/main/source/blender/blenkernel/BKE_blender_version.h

(by the way, if you join the blender-coders channel in blender.chat you should be able to get answer to those questions more quickly)
